### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [BrandoBie/4_TwitterBoostrap#1]
Hmm... it doesn't look like this HTML is actually the complete version of the Bootstrap project. Did you forget to do a final commit or `git push origin master`?

**Comment by BrandoBie** [comment]
Looks like I forgot to do a final commit. The updated should be the full project

**Comment by chrisvfritz** [comment]
:+1: Much better. Though in the future, it's better to put the "container" class on a `<div>`, _inside_ of the `<body>`, rather than on the `<body>` itself. When on the body, it's impossible to set a background for the page on wide screens and there may also be other side effects.
